# This is an example config file for btrfs-snapshot-manager.
#
# You will need to uncomment the below line to enable per-subvolume snapshots.
#
#subvolumes:

# For each subvolume you want to keep snapshots of, you need an entry
# here.
#
# Uncomment the below section to enable snapshots of the subvolume mounted
# to /.
#
#    # The 'path' field is the path on your filesystem the subvolume is
#    # mounted to.
#  - path: /
#    # The 'retention' section specifies how many snapshots for each time
#    # period will be retained.
#    retention:
#      hourly: 48
#      daily: 7
#      weekly: 3
#      monthly: 1

# Optional - Uncomment the next line to change the location of the snapshots
# subvolume, defaults to .snapshots. This path can be relative to the subvolume
# or absolute - e.g. "/snapshots".
#
#    snapshots-path: .snapshots

# Uncomment the next section to enable automatic backup of your snapshots to
# a local (e.g. a connected USB drive) or remote (e.g. NAS or server) location.
#
# Backups can be made using with btrfs - sending the subvolume snapshot to
# another btrfs filesystem - or using rsync.
#
# For each backup, you can specify how many snapshots for each time period will
# be kept on the target.
#
#    backup:
#
#      # Example: Btrfs, local backup
#      - type: btrfs
#        local:
#          path: /backups/btrfs/home
#        retention:
#          daily: 7
#          weekly: 3
#          monthly: 1
#        # Optional - After successful backup, a file in the source subvolume
#        # snapshots directory can be created with this name, to indicate the
#        # last time a successful backup run completed. This can be either
#        # relative to the snapshots directory, or absolute.
#        last_sync_file: .lastsync
#
#      # Example: Rsync, remote backup
#      - type: rsync
#        remote:
#          host: mybackupserver
#          user: backupuser
#          ssh-options: -i /root/.ssh/backupuser
#          path: /data/Backup/rsync/home
#        retention:
#          daily: 7
#          weekly: 3
#          monthly: 1

# Uncomment the next section to enable integration with the systemd-boot
# boot-loader. Boot loader entries are automatically generated, which you can
# then select in the boot menu to boot into the snapshot.
#
#    systemd-boot:
#
#      # This specifies the boot entry file in loader/entries to use as a
#      # reference when creating snapshot boot-loader entries.
#      - entry: linux.conf
#        # This section specifies how many snapshot boot-loader entries will be
#        # kept for each time period.
#        retention:
#          hourly: 5
#          daily: 7
#          weekly: 2
#          monthly: 1
#
#        # If you have multiple boot-loader entries, e.g. for different kernel
#        # versions, you can make snapshot boot-loader entries for each one
#        # with different retention settings.
#      - entry: linux-lts.conf
#        retention:
#          hourly: 3
#          daily: 2
#          weekly: 1


# Here is another subvolume for which snapshots could be generated
# and kept.
#  - path: /home
#    retention:
#      hourly: 48
#      daily: 7
#      weekly: 3
#      monthly: 3


# Uncomment the next section to configure global settings for the systemd-boot
# integration.
#systemd-boot:
#  # Optional - set the path to the boot partition, defaults to /boot
#  boot-path: /boot
#  # Optional - specify the files in the boot partition top-level to copy for
#  # each snapshot - by default all top-level files will be copied.
#  init-files:
#    - initramfs-linux.img
#    - initramfs-linux-lts.img
#    - vmlinuz-linux
#    - vmlinuz-linux-lts
