#!/bin/sh

# Install python script
cd "$(dirname "$0/")"
sudo pip3 install .

# Make config dir and empty config file
sudo mkdir -p /etc/btrfs-snapshot-manager
if [[ ! -f /etc/btrfs-snapshot-manager/config.yml ]]
then
    sudo cp config.yml /etc/btrfs-snapshot-manager/config.yml
fi

# Set up service and timer
PATHTOEXECUTABLE=`which btrfs-snapshot-manager | sed -e "s/\//\\\\\\\\\//g"`
sudo cp btrfs-snapshot.service /etc/systemd/system/
sudo sed -i -e "s/\/usr\/bin\/btrfs-snapshot-manager/$PATHTOEXECUTABLE/" /etc/systemd/system/btrfs-snapshot.service
sudo cp btrfs-snapshot.timer /etc/systemd/system/
sudo systemctl enable --now btrfs-snapshot.timer
